#!/usr/bin/env bash
set -euo pipefail

#################################################################
# Runs App Development Environment Startup
#
# Usage: ./dev-up.sh [options]
#
# Options:
#   --reset     Drop and recreate database (clean slate)
#   --acg       Write ACG sandbox DB credentials to .env (reads
#               ../consolidated-postgres/env/.env.acg)
#   --prod      Write prod (DigitalOcean) DB credentials to .env (reads
#               ../consolidated-postgres/env/.env.prod)
#   --help      Show this help message
#
# What it does:
#   1. Starts PostgreSQL in Docker
#   2. Waits for database to be ready
#   3. Creates/updates .env file with connection details
#   4. Runs Flyway migrations automatically (when app starts)
#
# Next steps:
#   mvn spring-boot:run
#   or use your IDE's "Run" button
#################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Configuration
CONTAINER_NAME="runs-app-postgres"
DB_NAME="runsapp_db"
DB_PORT=5443
HOST_PORT=5443
APP_PORT=8080
ACG_ENV_FILE="$SCRIPT_DIR/../consolidated-postgres/env/.env.acg"
PROD_ENV_FILE="$SCRIPT_DIR/../consolidated-postgres/env/.env.prod"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
RESET_DB=false
ACG_MODE=false
PROD_MODE=false
while [[ $# -gt 0 ]]; do
  case $1 in
    --reset)
      RESET_DB=true
      shift
      ;;
    --acg)
      ACG_MODE=true
      shift
      ;;
    --prod)
      PROD_MODE=true
      shift
      ;;
    --help)
      head -n 24 "$0" | tail -n +2
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

if $ACG_MODE && $PROD_MODE; then
  echo "--acg and --prod are mutually exclusive" >&2
  exit 1
fi

print_status() {
  echo -e "${GREEN}✓${NC} $1"
}

print_error() {
  echo -e "${RED}✗${NC} $1"
}

print_info() {
  echo -e "${YELLOW}ℹ${NC} $1"
}

print_warning() {
  echo -e "${YELLOW}⚠${NC} $1"
}

resolve_local_infra() {
  local candidate
  for candidate in \
      "$SCRIPT_DIR/../consolidated-postgres" \
      "$HOME/IdeaProjects/consolidated-postgres"; do
    if [ -f "$candidate/compose/docker-compose-local.yml" ]; then
      echo "$(cd "$candidate" && pwd)"
      return 0
    fi
  done
  return 1
}

run_psql_with_retry() {
  local user="$1"
  local db="$2"
  local sql="$3"
  local attempts="${4:-30}"
  local i

  for i in $(seq 1 "$attempts"); do
    if docker exec "$CONTAINER_NAME" psql -U "$user" -d "$db" -c "$sql" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done
  return 1
}

# Check if Docker is running
if ! docker ps > /dev/null 2>&1; then
  print_error "Docker is not running. Please start Docker and try again."
  exit 1
fi

print_info "Starting Runs App development environment..."

fetch_profile_value() {
  local file="$1" key="$2"
  if [ ! -f "$file" ]; then
    print_error "Profile configuration not found at $file"
    exit 1
  fi
  local value
  value=$(grep -E "^${key}=" "$file" | tail -n 1 | cut -d'=' -f2-)
  if [ -z "$value" ]; then
    print_error "Missing value for $key in $file"
    exit 1
  fi
  echo "$value"
}

fetch_infra_value() {
  local key="$1"
  local default_value="${2:-}"

  # Try to find infrastructure config in multiple locations
  local infra_paths=(
    "$SCRIPT_DIR/../consolidated-postgres/env/.env.local"
    "$HOME/IdeaProjects/consolidated-postgres/env/.env.local"
    "$SCRIPT_DIR/../../consolidated-postgres/env/.env.local"
  )

  for infra_file in "${infra_paths[@]}"; do
    if [ -f "$infra_file" ]; then
      local value
      value=$(grep -E "^${key}=" "$infra_file" | tail -n 1 | cut -d'=' -f2-)
      if [ -n "$value" ]; then
        echo "$value"
        return 0
      fi
    fi
  done

  # If not found and default provided, use default
  if [ -n "$default_value" ]; then
    print_info "Using default value for $key (infrastructure config not found)"
    echo "$default_value"
    return 0
  fi

  # If no default, warn but don't fail
  print_warning "Could not find $key in infrastructure config, using fallback"
  echo ""
  return 1
}

write_profile_env() {
  local profile_label="$1" flag="$2" jdbc_url="$3" username="$4" password="$5" host="$6" port="$7"

  # Fetch RabbitMQ credentials from infrastructure
  local rabbit_user=$(fetch_infra_value "RABBITMQ_USERNAME" "guest")
  local rabbit_pass=$(fetch_infra_value "RABBITMQ_PASSWORD" "guest")

  cat > .env << EOF
# Runs App $profile_label Database Configuration
# Generated by dev-up.sh $flag - do not commit to git

# Database Connection
JDBC_DATABASE_URL=$jdbc_url
JDBC_DATABASE_USERNAME=$username
JDBC_DATABASE_PASSWORD=$password

# RabbitMQ (from infrastructure config, override if using managed broker)
RABBITMQ_HOST=${RABBITMQ_HOST:-localhost}
RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
RABBITMQ_USERNAME=$rabbit_user
RABBITMQ_PASSWORD=$rabbit_pass

# Application Server
SERVER_PORT=$APP_PORT

# Flags
PRODUCTION=false
API_PATH=
EOF
  print_status "$profile_label .env file created"
}

if $ACG_MODE || $PROD_MODE; then
  if $ACG_MODE; then
    profile_label="ACG"; flag="--acg"; profile_file="$ACG_ENV_FILE"; start_script="./scripts/acg/acg-start.sh (or acg-aws-start.sh)"
  else
    profile_label="Prod"; flag="--prod"; profile_file="$PROD_ENV_FILE"; start_script="./scripts/prod/prod-start.sh"
  fi

  print_info "Configuring Runs App for $profile_label database..."
  jdbc_url=$(fetch_profile_value "$profile_file" "JDBC_DATABASE_URL")
  username=$(fetch_profile_value "$profile_file" "JDBC_DATABASE_USERNAME")
  password=$(fetch_profile_value "$profile_file" "JDBC_DATABASE_PASSWORD")

  url_body=${jdbc_url#jdbc:postgresql://}
  host_port=${url_body%%/*}
  db_and_query=${url_body#*/}
  host=${host_port%%:*}
  port=${host_port##*:}
  if [ -z "$host" ] || [ -z "$port" ]; then
    print_error "Unable to parse host/port from JDBC_DATABASE_URL in $profile_file"
    exit 1
  fi

  write_profile_env "$profile_label" "$flag" "$jdbc_url" "$username" "$password" "$host" "$port"
  print_status "Runs App configured for $profile_label database"
  cat <<EOT

════════════════════════════════════════════════════════════════
ℹ Runs App $profile_label configuration ready
════════════════════════════════════════════════════════════════

Database Details:
  Host:     $host
  Port:     $port
  User:     $username

Next Steps:
  1. Ensure $profile_label infrastructure is active ($start_script, from consolidated-postgres/)
  2. Run the application: mvn spring-boot:run

════════════════════════════════════════════════════════════════

EOT
  exit 0
fi

# Fetch credentials FIRST before docker compose
DB_USER=$(fetch_infra_value "RUNS_APP_DB_USER" "runsapp_local")
DB_PASSWORD=$(fetch_infra_value "RUNS_APP_DB_PASSWORD" "P4ssword!")
print_status "Using DB credentials from infra config (user: $DB_USER)"

# Fetch RabbitMQ credentials from infrastructure config
print_info "Fetching RabbitMQ credentials from infrastructure..."
RABBITMQ_USER=$(fetch_infra_value "RABBITMQ_USERNAME" "guest")
RABBITMQ_PASS=$(fetch_infra_value "RABBITMQ_PASSWORD" "guest")

if [ "$RABBITMQ_USER" = "guest" ] && [ "$RABBITMQ_PASS" = "guest" ]; then
  print_warning "Using default RabbitMQ credentials (guest/guest)"
  print_info "For production setup, ensure RabbitMQ is configured with proper credentials"
else
  print_status "Using RabbitMQ credentials from infrastructure config"
fi

# CREATE .env FILES BEFORE DOCKER COMPOSE
print_info "Creating .env and .env.development files..."
cat << EOF > .env
# Runs App Database Configuration
# Generated by dev-up.sh - do not commit to git

# Database Connection
JDBC_DATABASE_NAME=$DB_NAME
JDBC_DATABASE_URL=jdbc:postgresql://localhost:$HOST_PORT/$DB_NAME
JDBC_DATABASE_USERNAME=$DB_USER
JDBC_DATABASE_PASSWORD=$DB_PASSWORD

# RabbitMQ (from infrastructure config)
RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672
RABBITMQ_USERNAME=$RABBITMQ_USER
RABBITMQ_PASSWORD=$RABBITMQ_PASS

# Application Server
SERVER_PORT=$APP_PORT

# Garmin Import Configuration
GARMIN_SYSTEM_USER_ID=10000

# SMTP Configuration (optional - for email features)
SMTP_HOST=smtp.gmail.com
SMTP_USERNAME=your-email@gmail.com
SMTP_PASSWORD=your-app-password

# Email Display Settings
MAIL_FROM=noreply@example.com
MAIL_DISPLAY_NAME=Runs App

# Garmin CSV Import Alert Configuration
GARMIN_ALERT_EMAIL_ENABLED=true
GARMIN_ALERT_EMAIL_MAX_RETRY_ATTEMPTS=3
GARMIN_ALERT_EMAIL_RECIPIENTS=admin@example.com,devops@example.com
GARMIN_ALERT_EMAIL_FROM=garmin-import@example.com

# Google Drive Extended Configuration (for quarantine/retry)
GARMIN_DRIVE_FOLDER_ID=your-id
GARMIN_DRIVE_PROCESSED_FOLDER_ID=your_id_val
GARMIN_DRIVE_QUARANTINE_FOLDER_ID=your-quarantine-folder-id
GARMIN_DRIVE_FAILED_FOLDER_ID=your-failed-folder-id
GARMIN_DRIVE_RETRY_FOLDER_ID=your-retry-folder-id

# Sample Data Initialization (Dev Only)
# Enable sample data for local development with: ./mvnw spring-boot:run -Dspring-boot.run.profiles=dev
# See SECURITY_CONFIGURATION.md for more details
APP_INITIALIZATION_ENABLE_SAMPLE_DATA=false
APP_INITIALIZATION_ADMIN_EMAIL=admin@runsapp.com
APP_INITIALIZATION_ADMIN_PASSWORD=dev-admin-password
APP_INITIALIZATION_USER_EMAIL=runner@runsapp.com
APP_INITIALIZATION_USER_PASSWORD=dev-runner-password
APP_INITIALIZATION_SYSTEM_EMAIL=system@runsapp.com
APP_INITIALIZATION_SYSTEM_PASSWORD=dev-system-password

# Production flag
PRODUCTION=false
API_PATH=
EOF

cat << EOF > .env.development
# Runs App Database Configuration
# Generated by dev-up.sh - do not commit to git

# Database Connection
JDBC_DATABASE_NAME=$DB_NAME
JDBC_DATABASE_URL=jdbc:postgresql://localhost:$HOST_PORT/$DB_NAME
JDBC_DATABASE_USERNAME=$DB_USER
JDBC_DATABASE_PASSWORD=$DB_PASSWORD

# RabbitMQ (from infrastructure config)
RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672
RABBITMQ_USERNAME=$RABBITMQ_USER
RABBITMQ_PASSWORD=$RABBITMQ_PASS

# Application Server
SERVER_PORT=$APP_PORT

# Garmin Import Configuration
GARMIN_IMPORT_FOLDER=/data/garmin-fit-files
GARMIN_SYSTEM_USER_ID=10000

# SMTP Configuration (optional - for email features)
SMTP_HOST=smtp.gmail.com
SMTP_USERNAME=your-email@gmail.com
SMTP_PASSWORD=your-app-password

# Email Display Settings
MAIL_FROM=noreply@example.com
MAIL_DISPLAY_NAME=Runs App

# Garmin CSV Import Alert Configuration
GARMIN_ALERT_EMAIL_ENABLED=true
GARMIN_ALERT_EMAIL_MAX_RETRY_ATTEMPTS=3
GARMIN_ALERT_EMAIL_RECIPIENTS=admin@example.com,devops@example.com
GARMIN_ALERT_EMAIL_FROM=garmin-import@example.com

# Google Drive Extended Configuration (for quarantine/retry)
GARMIN_DRIVE_QUARANTINE_FOLDER_ID=your-quarantine-folder-id
GARMIN_DRIVE_FAILED_FOLDER_ID=your-failed-folder-id
GARMIN_DRIVE_RETRY_FOLDER_ID=your-retry-folder-id

# Sample Data Initialization (Dev Only)
# Enable sample data for local development with: ./mvnw spring-boot:run -Dspring-boot.run.profiles=dev
# See SECURITY_CONFIGURATION.md for more details
APP_INITIALIZATION_ENABLE_SAMPLE_DATA=false
APP_INITIALIZATION_ADMIN_EMAIL=admin@runsapp.com
APP_INITIALIZATION_ADMIN_PASSWORD=dev-admin-password
APP_INITIALIZATION_USER_EMAIL=runner@runsapp.com
APP_INITIALIZATION_USER_PASSWORD=dev-runner-password
APP_INITIALIZATION_SYSTEM_EMAIL=system@runsapp.com
APP_INITIALIZATION_SYSTEM_PASSWORD=dev-system-password

# Production flag
PRODUCTION=false
API_PATH=http://localhost:$APP_PORT
EOF

print_status ".env and .env.development files created"
print_info "If this project is deployed to VM/ACG/prod, re-sync: consolidated-postgres/scripts/vm/vm-db-up.sh runs-app"

LOCAL_INFRA_DIR="$(resolve_local_infra)" || {
  print_error "Cannot find consolidated-postgres — clone it as a sibling of runs-app"
  exit 1
}
LOCAL_COMPOSE_FILE="$LOCAL_INFRA_DIR/compose/docker-compose-local.yml"
LOCAL_ENV_FILE="$LOCAL_INFRA_DIR/env/.env.local"
compose() {
  docker compose -f "$LOCAL_COMPOSE_FILE" --env-file "$LOCAL_ENV_FILE" --profile runs-app "$@"
}

# Handle reset flag
# NOTE: this compose file is shared across projects (eventstracker, runs-ai-analyzer,
# mytracker, rabbitmq all live in it too) — never `compose down -v` here, that would
# wipe every sibling project's data. Only touch the runs-app-db service specifically.
if [ "$RESET_DB" = true ]; then
  print_info "Resetting database (--reset flag set)..."
  if docker container inspect "$CONTAINER_NAME" > /dev/null 2>&1; then
    compose rm -f -s -v runs-app-db
    docker volume rm runs-app_postgres-data 2>/dev/null || true
    print_status "Database reset"
  fi
fi

# Start Docker container
print_info "Starting PostgreSQL container..."
if docker container inspect "$CONTAINER_NAME" > /dev/null 2>&1 && docker ps --filter "name=$CONTAINER_NAME" | grep -q "$CONTAINER_NAME"; then
  print_status "PostgreSQL already running on port $HOST_PORT"
else
  compose up -d runs-app-db
  print_status "PostgreSQL started"
fi

# Wait for PostgreSQL to be ready
print_info "Waiting for PostgreSQL to be ready..."
max_attempts=30
attempt=0
_superuser=""

while [ $attempt -lt $max_attempts ]; do
  for _candidate in "$DB_USER" "${EVENTS_TRACKER_DB_USER:-}" "eventsvc_local" "postgres"; do
    [ -n "$_candidate" ] || continue
    if run_psql_with_retry "$_candidate" "postgres" "SELECT 1;" 1; then
      _superuser="$_candidate"
      print_status "PostgreSQL is ready"
      break 2
    fi
  done
  attempt=$((attempt + 1))
  sleep 1
done

if [ $attempt -eq $max_attempts ]; then
  print_error "PostgreSQL failed to start within ${max_attempts}s"
  print_info "Check logs with: docker logs $CONTAINER_NAME"
  exit 1
fi

[ -n "$_superuser" ] || {
  print_error "Could not find a working admin role in $CONTAINER_NAME"
  print_info "If this is an old volume with stale credentials, run: ./dev-up.sh --reset"
  exit 1
}

print_info "Container superuser: '${_superuser}', desired DB user: '${DB_USER}'"
run_psql_with_retry "$_superuser" "postgres" \
  "DO \$\$
   BEGIN
     CREATE ROLE \"${DB_USER}\" LOGIN PASSWORD '${DB_PASSWORD}';
   EXCEPTION WHEN duplicate_object THEN NULL;
   END \$\$;" 30 || {
  print_error "Failed to create/sync DB role ${DB_USER}"
  exit 1
}
run_psql_with_retry "$_superuser" "postgres" \
  "ALTER ROLE \"${DB_USER}\" WITH LOGIN PASSWORD '${DB_PASSWORD}';" 30 || {
  print_error "Failed to update password for DB role ${DB_USER}"
  exit 1
}
run_psql_with_retry "$_superuser" "postgres" \
  "GRANT ALL PRIVILEGES ON DATABASE \"${DB_NAME}\" TO \"${DB_USER}\";" 30 || true

# Verify database exists
print_info "Verifying database..."
if run_psql_with_retry "$DB_USER" "$DB_NAME" "SELECT 1;" 10; then
  print_status "Database verified"
else
  print_error "Failed to verify database"
  exit 1
fi

# Print next steps
echo ""
echo "════════════════════════════════════════════════════════════════"
echo -e "${GREEN}✓ Runs App is ready!${NC}"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Database Details:"
echo "  Host:     localhost"
echo "  Port:     $HOST_PORT"
echo "  Database: $DB_NAME"
echo "  User:     $DB_USER"
echo "  Password: $DB_PASSWORD"
echo ""
echo "Next Steps:"
echo "  1. Run the application WITH DEV PROFILE (for sample data initialization):"
echo "     mvn spring-boot:run -Dspring-boot.run.profiles=dev"
echo ""
echo "     Or run without dev profile (no sample data):"
echo "     mvn spring-boot:run"
echo ""
echo "  2. Or start React dev server (in separate terminal):"
echo "     npm run devserver"
echo ""
echo "  3. Flyway migrations will run automatically on startup"
echo ""
echo "  4. Access the application:"
echo "     Frontend (dev): http://localhost:3000"
echo "     Backend API:    http://localhost:$APP_PORT"
echo "     Health Check:   http://localhost:$APP_PORT/actuator/health"
echo ""
echo "  5. Review security configuration:"
echo "     See SECURITY_CONFIGURATION.md for environment variables and profiles"
echo ""
echo "Useful Commands:"
echo "  Stop database:    docker stop $CONTAINER_NAME"
echo "  View logs:        docker logs $CONTAINER_NAME"
echo "  Connect via psql: psql -h localhost -p $HOST_PORT -U $DB_USER -d $DB_NAME"
echo "  Reset database:   ./dev-up.sh --reset"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
