#!/usr/bin/env bash
set -euo pipefail

#################################################################
# Runs App Development Environment Startup
#
# Usage: ./dev-up.sh [options]
#
# Options:
#   --reset     Drop and recreate database (clean slate)
#   --help      Show this help message
#
# What it does:
#   1. Starts PostgreSQL in Docker
#   2. Waits for database to be ready
#   3. Creates/updates .env file with connection details
#   4. Runs Flyway migrations automatically (when app starts)
#   5. Includes ShedLock for distributed scheduling
#
# Next steps:
#   npm run devserver  (for React frontend, port 3000)
#   mvn spring-boot:run (for Java backend)
#
#################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Configuration
CONTAINER_NAME="runsapp-postgres"
DB_NAME="runsapp_db"
DB_USER="postgres"
DB_PASSWORD="postgres"
DB_PORT=5433  # Different from eventstracker to allow parallel dev
APP_PORT=8080
FRONTEND_PORT=3000

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
RESET_DB=false
while [[ $# -gt 0 ]]; do
  case $1 in
    --reset)
      RESET_DB=true
      shift
      ;;
    --help)
      head -n 20 "$0" | tail -n +2
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

print_status() {
  echo -e "${GREEN}✓${NC} $1"
}

print_error() {
  echo -e "${RED}✗${NC} $1"
}

print_info() {
  echo -e "${YELLOW}ℹ${NC} $1"
}

# Check if Docker is running
if ! docker ps > /dev/null 2>&1; then
  print_error "Docker is not running. Please start Docker and try again."
  exit 1
fi

print_info "Starting Runs App development environment..."

# Handle reset flag
if [ "$RESET_DB" = true ]; then
  print_info "Resetting database (--reset flag set)..."
  if docker container inspect "$CONTAINER_NAME" > /dev/null 2>&1; then
    docker compose -f docker-compose.dev.yml down -v
    print_status "Database reset"
  fi
fi

# Start Docker container
print_info "Starting PostgreSQL container..."
if docker container inspect "$CONTAINER_NAME" > /dev/null 2>&1 && docker ps --filter "name=$CONTAINER_NAME" | grep -q "$CONTAINER_NAME"; then
  print_status "PostgreSQL already running on port $DB_PORT"
else
  docker compose -f docker-compose.dev.yml up -d
  print_status "PostgreSQL started"
fi

# Wait for PostgreSQL to be ready
print_info "Waiting for PostgreSQL to be ready..."
max_attempts=30
attempt=0

while [ $attempt -lt $max_attempts ]; do
  if docker exec "$CONTAINER_NAME" pg_isready -U "$DB_USER" > /dev/null 2>&1; then
    print_status "PostgreSQL is ready"
    break
  fi
  attempt=$((attempt + 1))
  sleep 1
done

if [ $attempt -eq $max_attempts ]; then
  print_error "PostgreSQL failed to start within ${max_attempts}s"
  print_info "Check logs with: docker logs $CONTAINER_NAME"
  exit 1
fi

# Create .env file
print_info "Creating .env file..."
cat > .env << EOF
# Runs App Database Configuration
# Generated by dev-up.sh - do not commit to git

# Database Connection
DB_HOST=localhost
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
DB_USERNAME=$DB_USER
DB_PASSWORD=$DB_PASSWORD

# Full JDBC URL (used by Spring Boot)
JDBC_DATABASE_URL=jdbc:postgresql://localhost:$DB_PORT/$DB_NAME

# Spring Boot Specific
spring.datasource.url=jdbc:postgresql://localhost:$DB_PORT/$DB_NAME
spring.datasource.username=$DB_USER
spring.datasource.password=$DB_PASSWORD

# Alternative: Environment variable names expected by application.yml
JDBC_DATABASE_USERNAME=$DB_USER
JDBC_DATABASE_PASSWORD=$DB_PASSWORD

# RabbitMQ (for EventTracker event streaming)
RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672
RABBITMQ_USERNAME=guest
RABBITMQ_PASSWORD=guest

# Garmin Import Configuration
GARMIN_IMPORT_FOLDER=/data/garmin-fit-files
GARMIN_SYSTEM_USER_ID=10000

# Email Configuration (optional)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=your-email@gmail.com
SMTP_PASSWORD=your-app-password
MAIL_FROM=noreply@example.com

# Application
SERVER_PORT=$APP_PORT
BASE_HOST=http://localhost:$FRONTEND_PORT
