#!/usr/bin/env bash
set -euo pipefail

#################################################################
# Runs App Development Environment Startup
#
# Usage: ./dev-up.sh [options]
#
# Options:
#   --reset     Drop and recreate database (clean slate)
#   --help      Show this help message
#
# What it does:
#   1. Starts PostgreSQL in Docker
#   2. Waits for database to be ready
#   3. Creates/updates .env file with connection details
#   4. Runs Flyway migrations automatically (when app starts)
#
# Next steps:
#   mvn spring-boot:run
#   or use your IDE's "Run" button
#################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Configuration
CONTAINER_NAME="runs-app-postgres"
DB_NAME="runsapp_db"
DB_PORT=5443
HOST_PORT=5443
APP_PORT=8080
CLOUD_ENV_FILE="$SCRIPT_DIR/../consolidated-postgres/.env.cloud"
INFRA_ENV_FILE="$SCRIPT_DIR/../jubilant-memory/config/.env"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
RESET_DB=false
CLOUD_MODE=false
while [[ $# -gt 0 ]]; do
  case $1 in
    --reset)
      RESET_DB=true
      shift
      ;;
    --cloud)
      CLOUD_MODE=true
      shift
      ;;
    --help)
      head -n 20 "$0" | tail -n +2
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

print_status() {
  echo -e "${GREEN}✓${NC} $1"
}

print_error() {
  echo -e "${RED}✗${NC} $1"
}

print_info() {
  echo -e "${YELLOW}ℹ${NC} $1"
}

print_warning() {
  echo -e "${YELLOW}⚠${NC} $1"
}

run_psql_with_retry() {
  local user="$1"
  local db="$2"
  local sql="$3"
  local attempts="${4:-30}"
  local i

  for i in $(seq 1 "$attempts"); do
    if docker exec "$CONTAINER_NAME" psql -U "$user" -d "$db" -c "$sql" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done
  return 1
}

# Check if Docker is running
if ! docker ps > /dev/null 2>&1; then
  print_error "Docker is not running. Please start Docker and try again."
  exit 1
fi

print_info "Starting Runs App development environment..."

fetch_cloud_value() {
  local key="$1"
  if [ ! -f "$CLOUD_ENV_FILE" ]; then
    print_error "Cloud configuration not found at $CLOUD_ENV_FILE"
    exit 1
  fi
  local value
  value=$(grep -E "^${key}=" "$CLOUD_ENV_FILE" | tail -n 1 | cut -d'=' -f2-)
  if [ -z "$value" ]; then
    print_error "Missing value for $key in $CLOUD_ENV_FILE"
    exit 1
  fi
  echo "$value"
}

fetch_infra_value() {
  local key="$1"
  local default_value="${2:-}"

  # Try to find infrastructure config in multiple locations
  local infra_paths=(
    "$SCRIPT_DIR/../jubilant-memory/config/.env"
    "$HOME/IdeaProjects/jubilant-memory/config/.env"
    "$SCRIPT_DIR/../../jubilant-memory/config/.env"
  )

  for infra_file in "${infra_paths[@]}"; do
    if [ -f "$infra_file" ]; then
      local value
      value=$(grep -E "^${key}=" "$infra_file" | tail -n 1 | cut -d'=' -f2-)
      if [ -n "$value" ]; then
        echo "$value"
        return 0
      fi
    fi
  done

  # If not found and default provided, use default
  if [ -n "$default_value" ]; then
    print_info "Using default value for $key (infrastructure config not found)"
    echo "$default_value"
    return 0
  fi

  # If no default, warn but don't fail
  print_warning "Could not find $key in infrastructure config, using fallback"
  echo ""
  return 1
}

write_cloud_env() {
  local jdbc_url="$1"
  local username="$2"
  local password="$3"
  local host="$4"
  local port="$5"

  # Fetch RabbitMQ credentials from infrastructure
  local rabbit_user=$(fetch_infra_value "RABBITMQ_USERNAME" "guest")
  local rabbit_pass=$(fetch_infra_value "RABBITMQ_PASSWORD" "guest")

  cat > .env << EOF
# Runs App Cloud Database Configuration
# Generated by dev-up.sh --cloud - do not commit to git

# Database Connection
JDBC_DATABASE_URL=$jdbc_url
JDBC_DATABASE_USERNAME=$username
JDBC_DATABASE_PASSWORD=$password

# RabbitMQ (from infrastructure config, override if using managed broker)
RABBITMQ_HOST=${RABBITMQ_HOST:-localhost}
RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
RABBITMQ_USERNAME=$rabbit_user
RABBITMQ_PASSWORD=$rabbit_pass

# Application Server
SERVER_PORT=$APP_PORT

# Flags
PRODUCTION=false
API_PATH=
EOF
  print_status "Cloud .env file created"
}

if [ "$CLOUD_MODE" = true ]; then
  print_info "Configuring Runs App for DigitalOcean database..."
  jdbc_url=$(fetch_cloud_value "RUNSAPP_DATASOURCE_URL")
  username=$(fetch_cloud_value "RUNSAPP_DATASOURCE_USERNAME")
  password=$(fetch_cloud_value "RUNSAPP_DATASOURCE_PASSWORD")

  url_body=${jdbc_url#jdbc:postgresql://}
  host_port=${url_body%%/*}
  db_and_query=${url_body#*/}
  host=${host_port%%:*}
  port=${host_port##*:}
  if [ -z "$host" ] || [ -z "$port" ]; then
    print_error "Unable to parse host/port from RUNSAPP_DATASOURCE_URL"
    exit 1
  fi

  write_cloud_env "$jdbc_url" "$username" "$password" "$host" "$port"
  print_status "Runs App configured for cloud database"
  cat <<EOT

════════════════════════════════════════════════════════════════
ℹ Runs App cloud configuration ready
════════════════════════════════════════════════════════════════

Database Details:
  Host:     $host
  Port:     $port
  User:     $username

Next Steps:
  1. Ensure cloud infrastructure is active (./cloud-start.sh)
  2. Run the application: mvn spring-boot:run

════════════════════════════════════════════════════════════════

EOT
  exit 0
fi

# Fetch credentials FIRST before docker compose
DB_USER=$(fetch_infra_value "RUNS_APP_DB_USER" "runsapp_local")
DB_PASSWORD=$(fetch_infra_value "RUNS_APP_DB_PASSWORD" "P4ssword!")
print_status "Using DB credentials from infra config (user: $DB_USER)"

# Fetch RabbitMQ credentials from infrastructure config
print_info "Fetching RabbitMQ credentials from infrastructure..."
RABBITMQ_USER=$(fetch_infra_value "RABBITMQ_USERNAME" "guest")
RABBITMQ_PASS=$(fetch_infra_value "RABBITMQ_PASSWORD" "guest")

if [ "$RABBITMQ_USER" = "guest" ] && [ "$RABBITMQ_PASS" = "guest" ]; then
  print_warning "Using default RabbitMQ credentials (guest/guest)"
  print_info "For production setup, ensure RabbitMQ is configured with proper credentials"
else
  print_status "Using RabbitMQ credentials from infrastructure config"
fi

# CREATE .env FILES BEFORE DOCKER COMPOSE
print_info "Creating .env and .env.development files..."
cat << EOF > .env
# Runs App Database Configuration
# Generated by dev-up.sh - do not commit to git

# Database Connection
JDBC_DATABASE_NAME=$DB_NAME
JDBC_DATABASE_URL=jdbc:postgresql://localhost:$HOST_PORT/$DB_NAME
JDBC_DATABASE_USERNAME=$DB_USER
JDBC_DATABASE_PASSWORD=$DB_PASSWORD

# RabbitMQ (from infrastructure config)
RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672
RABBITMQ_USERNAME=$RABBITMQ_USER
RABBITMQ_PASSWORD=$RABBITMQ_PASS

# Application Server
SERVER_PORT=$APP_PORT

# Garmin Import Configuration
GARMIN_SYSTEM_USER_ID=10000

# SMTP Configuration (optional - for email features)
SMTP_HOST=smtp.gmail.com
SMTP_USERNAME=your-email@gmail.com
SMTP_PASSWORD=your-app-password

# Email Display Settings
MAIL_FROM=noreply@example.com
MAIL_DISPLAY_NAME=Runs App

# Garmin CSV Import Alert Configuration
GARMIN_ALERT_EMAIL_ENABLED=true
GARMIN_ALERT_EMAIL_MAX_RETRY_ATTEMPTS=3
GARMIN_ALERT_EMAIL_RECIPIENTS=admin@example.com,devops@example.com
GARMIN_ALERT_EMAIL_FROM=garmin-import@example.com

# Google Drive Extended Configuration (for quarantine/retry)
GARMIN_DRIVE_FOLDER_ID=your-id
GARMIN_DRIVE_PROCESSED_FOLDER_ID=your_id_val
GARMIN_DRIVE_QUARANTINE_FOLDER_ID=your-quarantine-folder-id
GARMIN_DRIVE_FAILED_FOLDER_ID=your-failed-folder-id
GARMIN_DRIVE_RETRY_FOLDER_ID=your-retry-folder-id

# Production flag
PRODUCTION=false
API_PATH=
EOF

cat << EOF > .env.development
# Runs App Database Configuration
# Generated by dev-up.sh - do not commit to git

# Database Connection
JDBC_DATABASE_NAME=$DB_NAME
JDBC_DATABASE_URL=jdbc:postgresql://localhost:$HOST_PORT/$DB_NAME
JDBC_DATABASE_USERNAME=$DB_USER
JDBC_DATABASE_PASSWORD=$DB_PASSWORD

# RabbitMQ (from infrastructure config)
RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672
RABBITMQ_USERNAME=$RABBITMQ_USER
RABBITMQ_PASSWORD=$RABBITMQ_PASS

# Application Server
SERVER_PORT=$APP_PORT

# Garmin Import Configuration
GARMIN_IMPORT_FOLDER=/data/garmin-fit-files
GARMIN_SYSTEM_USER_ID=10000

# SMTP Configuration (optional - for email features)
SMTP_HOST=smtp.gmail.com
SMTP_USERNAME=your-email@gmail.com
SMTP_PASSWORD=your-app-password

# Email Display Settings
MAIL_FROM=noreply@example.com
MAIL_DISPLAY_NAME=Runs App

# Garmin CSV Import Alert Configuration
GARMIN_ALERT_EMAIL_ENABLED=true
GARMIN_ALERT_EMAIL_MAX_RETRY_ATTEMPTS=3
GARMIN_ALERT_EMAIL_RECIPIENTS=admin@example.com,devops@example.com
GARMIN_ALERT_EMAIL_FROM=garmin-import@example.com

# Google Drive Extended Configuration (for quarantine/retry)
GARMIN_DRIVE_QUARANTINE_FOLDER_ID=your-quarantine-folder-id
GARMIN_DRIVE_FAILED_FOLDER_ID=your-failed-folder-id
GARMIN_DRIVE_RETRY_FOLDER_ID=your-retry-folder-id

# Production flag
PRODUCTION=false
API_PATH=http://localhost:$APP_PORT
EOF

print_status ".env and .env.development files created"

# Handle reset flag
if [ "$RESET_DB" = true ]; then
  print_info "Resetting database (--reset flag set)..."
  if docker container inspect "$CONTAINER_NAME" > /dev/null 2>&1; then
    docker compose down -v
    print_status "Database reset"
  fi
fi

# Start Docker container
print_info "Starting PostgreSQL container..."
if docker container inspect "$CONTAINER_NAME" > /dev/null 2>&1 && docker ps --filter "name=$CONTAINER_NAME" | grep -q "$CONTAINER_NAME"; then
  print_status "PostgreSQL already running on port $HOST_PORT"
else
  docker compose up -d
  print_status "PostgreSQL started"
fi

# Wait for PostgreSQL to be ready
print_info "Waiting for PostgreSQL to be ready..."
max_attempts=30
attempt=0
_superuser=""

while [ $attempt -lt $max_attempts ]; do
  for _candidate in "$DB_USER" "${EVENTS_TRACKER_DB_USER:-}" "eventsvc_local" "postgres"; do
    [ -n "$_candidate" ] || continue
    if run_psql_with_retry "$_candidate" "postgres" "SELECT 1;" 1; then
      _superuser="$_candidate"
      print_status "PostgreSQL is ready"
      break 2
    fi
  done
  attempt=$((attempt + 1))
  sleep 1
done

if [ $attempt -eq $max_attempts ]; then
  print_error "PostgreSQL failed to start within ${max_attempts}s"
  print_info "Check logs with: docker logs $CONTAINER_NAME"
  exit 1
fi

[ -n "$_superuser" ] || {
  print_error "Could not find a working admin role in $CONTAINER_NAME"
  print_info "If this is an old volume with stale credentials, run: ./dev-up.sh --reset"
  exit 1
}

print_info "Container superuser: '${_superuser}', desired DB user: '${DB_USER}'"
run_psql_with_retry "$_superuser" "postgres" \
  "DO \$\$
   BEGIN
     CREATE ROLE \"${DB_USER}\" LOGIN PASSWORD '${DB_PASSWORD}';
   EXCEPTION WHEN duplicate_object THEN NULL;
   END \$\$;" 30 || {
  print_error "Failed to create/sync DB role ${DB_USER}"
  exit 1
}
run_psql_with_retry "$_superuser" "postgres" \
  "ALTER ROLE \"${DB_USER}\" WITH LOGIN PASSWORD '${DB_PASSWORD}';" 30 || {
  print_error "Failed to update password for DB role ${DB_USER}"
  exit 1
}
run_psql_with_retry "$_superuser" "postgres" \
  "GRANT ALL PRIVILEGES ON DATABASE \"${DB_NAME}\" TO \"${DB_USER}\";" 30 || true

# Verify database exists
print_info "Verifying database..."
if run_psql_with_retry "$DB_USER" "$DB_NAME" "SELECT 1;" 10; then
  print_status "Database verified"
else
  print_error "Failed to verify database"
  exit 1
fi

# Print next steps
echo ""
echo "════════════════════════════════════════════════════════════════"
echo -e "${GREEN}✓ Runs App is ready!${NC}"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Database Details:"
echo "  Host:     localhost"
echo "  Port:     $HOST_PORT"
echo "  Database: $DB_NAME"
echo "  User:     $DB_USER"
echo "  Password: $DB_PASSWORD"
echo ""
echo "Next Steps:"
echo "  1. Run the application:"
echo "     mvn spring-boot:run"
echo ""
echo "  2. Or start React dev server (in separate terminal):"
echo "     npm run devserver"
echo ""
echo "  3. Flyway migrations will run automatically on startup"
echo ""
echo "  4. Access the application:"
echo "     Frontend (dev): http://localhost:3000"
echo "     Backend API:    http://localhost:$APP_PORT"
echo "     Health Check:   http://localhost:$APP_PORT/actuator/health"
echo ""
echo "Useful Commands:"
echo "  Stop database:    docker compose down"
echo "  View logs:        docker logs $CONTAINER_NAME"
echo "  Connect via psql: psql -h localhost -p $HOST_PORT -U $DB_USER -d $DB_NAME"
echo "  Reset database:   ./dev-up.sh --reset"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
